apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  namespace: triton-monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: triton-is-predictor
  endpoints:
    - port: metrics
      interval: 5s
      path: /metrics
