{
 "title": "KServe Triton Latency",
 "description": "KServe Triton Latency Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "GPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nv_gpu_memory_used_bytes)", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "KServe Triton Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "predict latency rate (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us[10m]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "preprocess latency rate (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_input_duration_us[3m]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "postprocess latency rate (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_output_duration_us[10m]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "total triton latency rate (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_request_duration_us[10m]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[10m]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}